=== typ49/Semestre_6/xml/TP/for-lc-1/poemefr0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--  Premier essai, constituÃ© exclusivement d'Ã©lÃ©ments -->

<!ELEMENT poemefr0   (preambule,corps)>
<!ELEMENT preambule  (titre,recueil?,date?,auteur)>
<!ELEMENT titre      (#PCDATA)>
<!ELEMENT recueil    (#PCDATA)>
<!ELEMENT date       (#PCDATA)>
<!ELEMENT auteur     (prenom?,nom,naissance?,deces?)>
<!ELEMENT prenom     (#PCDATA)>
<!ELEMENT nom        (#PCDATA)>
<!ELEMENT naissance  (#PCDATA)>
<!ELEMENT deces      (#PCDATA)>
<!ELEMENT corps      (strophe+)>
<!ELEMENT strophe    (ligne+)>
<!ELEMENT ligne      (#PCDATA | r)*>
<!ELEMENT r          EMPTY>

=== typ49/Semestre_6/xml/TP/for-lc-1/automne-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="poemefr0.css" type="text/css"?>
<!--  Première version avec utilisation exclusive d'éléments -->
<!DOCTYPE poemefr0 SYSTEM "poemefr0.dtd">

<poemefr0>
  <preambule>
    <titre>Chanson d'automne</titre>
    <recueil>Poèmes saturniens</recueil>
    <date>1866</date>
    <auteur>
      <prenom>Paul</prenom>
      <nom>Verlaine</nom>
      <naissance>1844</naissance>
      <deces>1896</deces>
    </auteur>
  </preambule>
  <corps>
    <strophe>
      <ligne>Les sanglots longs</ligne>
      <ligne>Des violons</ligne>
      <ligne><r />De l'automne</ligne>
      <ligne>Blessent mon cœur</ligne>
      <ligne>D'une langueur</ligne>
      <ligne><r />Monotone.</ligne>
    </strophe>
    <strophe>
      <ligne>Tout suffocant,</ligne>
      <ligne>Et blême, quand</ligne>
      <ligne><r />Sonne l'heure,</ligne>
    </strophe>
    <strophe>
      <ligne>Je me souviens</ligne>
      <ligne>Des jours anciens</ligne>
      <ligne><r />Et je pleure ;</ligne>
    </strophe>
    <strophe>
      <ligne>Et je m'en vais</ligne>
      <ligne>Au vent mauvais</ligne>
      <ligne><r />Qui m'emporte</ligne>
      <ligne>Deça, delà,</ligne>
      <ligne>Pareil à la</ligne>
      <ligne><r />Feuille morte.</ligne>
    </strophe>
  </corps>
</poemefr0>

=== typ49/Semestre_6/xml/tp/for-lc-2/included/several-i.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Exemple d'utilisation d'"XInclude". Attention ! il faut répéter la
      déclaration de l'élément "poemefr0", car cet élément n'est pas reconnu
      par la seule déclaration "ATTLIST poemefr0 ...", visant à lui ajouter
      l'attribut portant l'espace de noms d'"XInclude". Rappelons en outre que
      cet ajout de définitions locales pour les attributs de la forme
      "xmlns:..." est inutile si le texte est décrit au moyen d'un schéma.
  -->

<!DOCTYPE poemefr0 SYSTEM "poemefr0.dtd"
  [<!ELEMENT poemefr0  (preambule,corps)>
   <!ATTLIST poemefr0 xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude"
                      xml:base CDATA #IMPLIED>]>

<poemefr0 xmlns:xi="http://www.w3.org/2001/XInclude">

  <preambule>
    <titre>Chanson d'automne</titre>
    <recueil>
      <xi:include href="several-3.txt" parse="text" encoding="UTF-8">
        <xi:fallback>Recueil inconnu ou inexistant</xi:fallback>
      </xi:include>
    </recueil>
    <date>1866</date>
    <auteur>
      <prenom>Paul</prenom>
      <nom>Verlaine</nom>
      <naissance>1844</naissance>
      <deces>1896</deces>
    </auteur>
  </preambule>

  <corps>
    <xi:include href="several-1.xml" parse="xml"/>
    <xi:include href="several-2.xml"/>
    <xi:include href="silent.xml" xml:base="somewhere">
      <xi:fallback/>
    </xi:include>
    <strophe>
      <ligne>Je me souviens</ligne>
      <ligne>Des jours anciens</ligne>
      <ligne><r/>Et je pleure ;</ligne>
    </strophe>
    <strophe>
      <ligne>Et je m'en vais</ligne>
      <ligne>Au vent mauvais</ligne>
      <ligne><r/>Qui m'emporte</ligne>
      <ligne>Deça, delà,</ligne>
      <ligne>Pareil à la</ligne>
      <ligne><r/>Feuille morte.</ligne>
    </strophe>
  </corps>

</poemefr0>

=== typ49/Semestre_6/xml/tp/for-lc-2/included/several.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE poemefr0 SYSTEM "poemefr0.dtd" [<!ENTITY s1 SYSTEM "several-1.xml">
                                          <!ENTITY s2 SYSTEM "several-2.xml">]>
  
<poemefr0>

  <preambule>
    <titre>Chanson d'automne</titre>
    <recueil>Poèmes saturniens</recueil>
    <date>1866</date>
    <auteur>
      <prenom>Paul</prenom>
      <nom>Verlaine</nom>
      <naissance>1844</naissance>
      <deces>1896</deces>
    </auteur>
  </preambule>

  <corps>
    &s1;
    &s2;
    <strophe>
      <ligne>Je me souviens</ligne>
      <ligne>Des jours anciens</ligne>
      <ligne><r/>Et je pleure ;</ligne>
    </strophe>
    <strophe>
      <ligne>Et je m'en vais</ligne>
      <ligne>Au vent mauvais</ligne>
      <ligne><r/>Qui m'emporte</ligne>
      <ligne>Deça, delà,</ligne>
      <ligne>Pareil à la</ligne>
      <ligne><r/>Feuille morte.</ligne>
    </strophe>
  </corps>
  
</poemefr0>
